### ISSUE TITLE
term2@0.9.4 is not working on Atom Editor v0.169.0

### ISSUE THREAD

**Issue by MiquelAdell** [webBoxio/atom-term2#83]
Atom says:

The following packages could not be loaded because they contain native modules that aren't compatible with this version of Atom.

Previous Atom versions shipped with Chrome 31 and Node 0.11.10 but Atom now ships with Chrome 39.0.2171.65 and Node 0.13.0-pre.

The packages listed should now ship versions of these native modules that are compatible with Node 0.13.0-pre.

Updates for these packages may already be available that resolve this issue.

If no update is available you may want to notify the package author that their package isn't supported in Atom 0.169.0 because of the Chrome 39.0.2171.65 and Node 0.13.0-pre upgrade.

If you think a package is listed here and should no longer be, click the button below to reload Atom and recheck all packages.

Listed below are the incompatible native modules that this package depends on.

pty.js@0.2.4
Error message: Module version mismatch. Expected 17, got 16.

**Comment by agektmr** [comment]
I have the same issue and that causes Term2 completely unusable.

**Comment by carlosbaraza** [comment]
:+1:

**Comment by ccodewa** [comment]
try
rm -rf node_modules && apm install
in the term2 package directory to recompile the dependencies.

**Comment by agektmr** [comment]
@ccodewa no luck.

**Comment by carlosbaraza** [comment]
Hi, the issue is on the version of `mocha` used by the `pty.js` dependency. To fix it I just changed manually the dependency to a fork where I have modified the version of mocha. So, in the `package.json`:

```javascript
"pty.js": "https://github.com/carlosbaraza/pty.js/archive/master.tar.gz"
```

Then you should recompile the dependencies of the package with `rm -rf node_modules && apm install` in the `term2` folder. Finally, restart atom and "voila!".

So, I will do a pull request to bump the mocha version in the `pty.js` library.

**Comment by agektmr** [comment]
Simply deleting and reinstalling term2 worked for me. The problem seems to be fixed.

**Comment by MoOx** [comment]
Should be good now.
